export type ChangeLogUpdate = {
  id: string;
  occurredAt: string;
  title: string;
  description: string;
  category: 'Frontend' | 'Backend' | 'DevOps' | 'Hermes' | 'General';
};

// Tambahkan satu entri untuk setiap permintaan perubahan yang selesai diterapkan.
// Gunakan timestamp ISO dengan zona waktu agar sorting dan filter tanggal tetap akurat.
export const changeLogUpdates: ChangeLogUpdate[] = [
  {
    id: '2026-09-23-learning-home-journey',
    occurredAt: '2026-09-23T23:08:47+07:00',
    title: 'Beranda Learning Jejak Belajar terhubung ke sesi',
    description: 'Mengubah /learning menjadi pintu masuk Jejak Belajar dengan ringkasan berbasis sesi tersimpan, linimasa, pencarian dan filter, pengingat review dari tanggal sesi, pertanyaan yang belum jelas, serta pintasan modul, rencana sesi, katalog, dan jurnal kalender lama di /learning/journal. Jurnal lama tetap dapat dikelola; isolasi akun pada data jurnal diperketat agar cache atau respons terlambat tidak terbawa ke akun lain, dan kegagalan memuat kini ditandai dengan opsi coba lagi tanpa menampilkan kosong palsu atau menimpa perubahan terbaru. Verifikasi: 131 test frontend, build produksi, dan 41 pemeriksaan browser terisolasi dengan PostgreSQL sementara termasuk tema gelap/terang serta lebar 320/390 px.',
    category: 'Frontend',
  },
  {
    id: '2026-09-23-learning-manual-modules-sessions',
    occurredAt: '2026-09-23T18:32:44+07:00',
    title: 'Modul dan sesi belajar manual dengan refleksi wajib',
    description: 'Menambahkan modul Learning berisi materi teks, tautan, PDF, dan video; perencanaan sesi per bagian materi; serta Notes refleksi yang wajib sebelum sesi selesai. Modul, materi, file, dan sesi tersimpan melalui API Go dan PostgreSQL dengan validasi, hak akses pengguna/admin, dan pembacaan ulang. Verifikasi: 114 test frontend, build produksi, test Go dengan PostgreSQL terisolasi, serta 28 pemeriksaan browser terisolasi termasuk reload dan mobile.',
    category: 'General',
  },
  {
    id: '2026-09-23-doing-complete-workspace',
    occurredAt: '2026-09-23T11:43:48+07:00',
    title: 'Doing Complete Workspace terhubung ke PostgreSQL',
    description: 'Merombak halaman Doing menjadi workspace dengan daftar, kalender Planned Date, filter, detail dan editor 23 atribut, Notes multiline, serta checklist persisten. Menambah API Go dan migrasi additive yang mempertahankan 33 task lama beserta metadata historis. Verifikasi: 108 test frontend, test Go dan PostgreSQL terisolasi, authenticated API roundtrip/ownership/CSRF, build Docker serta browser served pada desktop dan mobile 320/390 px.',
    category: 'General',
  },
  {
    id: '2026-09-15-personal-overview-motion',
    occurredAt: '2026-09-15T15:49:47+07:00',
    title: 'Overview personal interaktif tersedia',
    description: 'Mengubah Overview menjadi ringkasan personal untuk Doing, Learning, Workout, Journaling, dan Spending dengan fokus hari ini, aktivitas milik pengguna, quick actions ke form asli, preview Change Log, serta Session Observability yang tetap dapat dicari. Menambahkan pointer dan scroll parallax, hover tilt ringan, reveal satu kali, kontrol motion tersimpan, reduced-motion, state loading/empty/partial failure, tema existing, dan profil tipografi Compact, Standard, serta Expanded.',
    category: 'Frontend',
  },
  {
    id: '2026-08-22-change-log-time-groups',
    occurredAt: '2026-08-22T23:54:16+07:00',
    title: 'Pembagian waktu dan tab baru pada Change Log',
    description: 'Menambahkan tab Session Entries dan Log Update dengan layout responsif. Setiap update kini dicatat per tanggal, dapat diurutkan, serta difilter berdasarkan Hari ini, Kemarin, Minggu ini, dan Lebih lama.',
    category: 'Frontend',
  },
  {
    id: '2026-08-23-remove-session-entries-tab',
    occurredAt: '2026-08-23T00:28:50+07:00',
    title: 'Change Log langsung menampilkan Log Update',
    description: 'Menghapus tab Session Entries beserta navigasi tab. Halaman Change Log kini langsung menampilkan daftar Log Update, filter waktu, dan pengurutan.',
    category: 'Frontend',
  },
  {
    id: '2026-08-23-go-postgres-swagger-backend',
    occurredAt: '2026-08-23T00:39:40+07:00',
    title: 'Backend Go, PostgreSQL, dan Swagger siap digunakan',
    description: 'Mengganti backend Node.js menjadi Go dengan struktur ringkas, mempertahankan kontrak API dashboard, mengaktifkan migrasi otomatis dan persistence PostgreSQL lokal, serta menyediakan OpenAPI 3.0.3 dan Swagger UI. Test, build, health check, CRUD API, pembacaan database, dan render Swagger telah diverifikasi berhasil.',
    category: 'Backend',
  },
  {
    id: '2026-08-23-session-dashboard-learning-update',
    occurredAt: '2026-08-23T00:44:17+07:00',
    title: 'Pembaruan lengkap dashboard dan Learning Journal',
    description: 'Merangkum pembaruan sesi ini: dark/light mode, sidebar modern dan konsisten, route URL per halaman, koneksi frontend ke API Go/PostgreSQL, kalender Learning lintas tahun, tambah/edit/delete/checklist, tiga item dengan internal scroll yang mempertahankan posisi, icon action, popover konfirmasi delete, dropdown sesuai tema, serta penanda kalender berbeda untuk task in progress dan seluruh task selesai.',
    category: 'General',
  },
  {
    id: '2026-08-23-change-log-postgres-api',
    occurredAt: '2026-08-23T00:59:14+07:00',
    title: 'Change Log dipersist ke PostgreSQL',
    description: 'Menambahkan tabel Change Log, endpoint GET dan POST pada backend Go, migrasi entri existing, serta integrasi frontend agar membaca data dari API dengan fallback lokal saat backend tidak tersedia.',
    category: 'Backend',
  },
  {
    id: '2026-08-23-lifestyle-pages',
    occurredAt: '2026-08-23T01:14:29+07:00',
    title: 'Workout, Journaling, dan Spending tersedia',
    description: 'Menambahkan tiga page bergaya Learning yang terhubung ke PostgreSQL: kalender dan checklist Workout, Journaling dengan tab Arsip serta Ruang Tulis berfitur Markdown, autosave draft, live preview, toolbar, shortcut, dan mode fokus, serta Spending dengan ledger dan ringkasan total harian, mingguan, bulanan, dan tahunan.',
    category: 'General',
  },
  {
    id: '2026-08-23-calendar-unfinished-badges',
    occurredAt: '2026-08-23T02:35:19+07:00',
    title: 'Badge kalender menghitung task yang belum selesai',
    description: 'Mengubah badge angka pada kalender Learning dan Workout agar menampilkan jumlah task unfinished, bukan jumlah seluruh task. Jika hanya satu task belum selesai, badge kini menampilkan 1; hari yang seluruh task-nya selesai tetap menggunakan tanda centang.',
    category: 'Frontend',
  },
  {
    id: '2026-08-23-doing-page',
    occurredAt: '2026-08-23T11:35:17+07:00',
    title: 'Page Doing tersedia di atas Learning',
    description: 'Menambahkan page Doing dengan kalender lintas bulan dan tahun, task per tanggal, unfinished badge, tambah, edit, delete, checklist, scroll preservation, route /doing, serta persistence PostgreSQL melalui API Go. Item Doing ditempatkan tepat di atas Learning pada sidebar.',
    category: 'General',
  },
  {
    id: '2026-08-23-zeno-rebrand',
    occurredAt: '2026-08-23T12:06:02+07:00',
    title: 'Project berganti nama menjadi Zeno',
    description: 'Mengganti branding project dari Hermes menjadi Zeno pada UI, metadata, API, dokumentasi, package, dan Docker. Logo Z dari pengguna kini digunakan pada sidebar, favicon multi-size, Apple touch icon, dan web app manifest.',
    category: 'General',
  },
  {
    id: '2026-08-23-zeno-color-system',
    occurredAt: '2026-08-23T12:23:35+07:00',
    title: 'Nuansa warna Zeno diterapkan pada dark dan light mode',
    description: 'Menerapkan palet Z Navy, Z Blue, Z Cyan, dan Z White sebagai token source-of-truth. Surface, border, teks, CTA, selected navigation, kalender, status, focus glow, serta komponen Workout, Journaling, dan Spending kini konsisten dalam dark dan light mode tanpa aksen purple legacy.',
    category: 'Frontend',
  },
  {
    id: '2026-08-23-auth-activity-ownership',
    occurredAt: '2026-08-23T13:49:10+07:00',
    title: 'Authentication, authorization, profile, dan user activity tersedia',
    description: 'Menambahkan register email/password, email verification sekali pakai, login, logout, profile, bcrypt password, opaque HttpOnly session, rate limiting, origin check, role admin/user, ownership record, dan Activity audit berbasis actor/action/entity. Admin melihat seluruh activity dan record; user biasa hanya miliknya. Email mendukung Resend, SMTP, dan file outbox development.',
    category: 'General',
  },
  {
    id: '2026-08-24-git-monorepo-ci',
    occurredAt: '2026-08-24T10:59:15+07:00',
    title: 'Git monorepo dan CI GitHub tersedia',
    description: 'Menginisialisasi Zeno sebagai satu monorepo pada branch main, menghubungkannya ke Rama-z/zeno-dashboard, menambahkan ignore rules untuk secret dan runtime artifact, dokumentasi root, serta GitHub Actions untuk format, vet, test PostgreSQL, build backend, build frontend, dan build Docker. Initial push, fresh clone, secret scan, dan CI pertama telah diverifikasi berhasil.',
    category: 'DevOps',
  },
  {
    id: '2026-08-24-dashboard-compact-redesign',
    occurredAt: '2026-08-24T13:02:56+07:00',
    title: 'Dashboard overview dipadatkan dengan visual Zeno',
    description: 'Merapikan shell dashboard, memperlebar area konten, memadatkan spacing heading, metric, toolbar, dan row session, serta menjaga state expand, filter, sidebar, responsive layout, dan dark/light mode.',
    category: 'Frontend',
  },
  {
    id: '2026-08-24-landing-page-v2',
    occurredAt: '2026-08-24T13:53:50+07:00',
    title: 'Landing page V2 Zeno tersedia',
    description: 'Menambahkan landing publik kreatif dan interaktif di root untuk pengunjung anonim, enam aset visual Zeno teroptimasi, observability tabs, personal workspace selector, ownership switch, dual theme, responsive mobile navigation, reduced motion, self-hosted fonts, serta CTA ke login tanpa mengubah route dashboard pengguna terautentikasi.',
    category: 'Frontend',
  },
  {
    id: '2026-08-24-dashboard-precision-redesign',
    occurredAt: '2026-08-24T16:02:37+07:00',
    title: 'Dashboard Zeno memakai precision redesign',
    description: 'Meredesain seluruh shell dashboard dengan Outfit dan Phosphor Icons, grouped navigation Observe, Personal, dan Account, floating sidebar serta topbar, asymmetric metrics, session rows yang lebih padat, global search yang berfungsi, skip link, shared premium surfaces, responsive collapsed rail, dark/light parity, dan reduced motion tanpa mengubah route maupun behavior data.',
    category: 'Frontend',
  },
  {
    id: '2026-08-26-journal-revision-history',
    occurredAt: '2026-08-26T00:17:04+07:00',
    title: 'Riwayat revisi Journaling Zeno tersedia',
    description: 'Menambahkan deliberate edit dengan empat reason code stabil, immutable journal revisions, lazy newest-first history, navigasi swipe/pointer/keyboard yang accessible, optimistic concurrency, audit metadata tanpa isi jurnal, dan cascade delete untuk seluruh revisi.',
    category: 'Frontend',
  },
  {
    id: '2026-08-26-learning-material-foundation',
    occurredAt: '2026-08-26T01:08:31+07:00',
    title: 'Fondasi Learning Material List tersedia',
    description: 'Menyusun kurikulum English Grammar A1–C1 berbasis riset British Council, BBC, Cambridge, Oxford, dan CEFR; menambahkan empat lesson JSON representatif lintas level; serta menyiapkan implementation brief mandiri untuk Luna tanpa membangun UI, adaptive engine, CMS, atau schema progress penuh.',
    category: 'General',
  },
  {
    id: '2026-08-26-learning-material-list',
    occurredAt: '2026-08-26T09:58:49+07:00',
    title: 'Learning Material List prototype tersedia',
    description: 'Menambahkan route nested tanpa router dependency, catalogue English Grammar dari manifest JSON, empat lesson static lintas level, halaman Concept sampai Review, practice dan objective-aware quiz dengan feedback, filter topic, validasi konten build-time, dan label prototype bahwa progress belum disimpan.',
    category: 'Frontend',
  },
  {
    id: '2026-08-26-font-profile-preferences',
    occurredAt: '2026-08-26T10:35:05+07:00',
    title: 'Pilihan font profile tersedia di UI',
    description: 'Menambahkan pengaturan tipografi Compact, Standard, dan Expanded di Appearance. Compact mempertahankan kepadatan saat ini sebagai default; pilihan disimpan di browser dan diterapkan ke ukuran heading, ukuran teks, line-height, dan letter-spacing dashboard.',
    category: 'Frontend',
  },
  {
    id: '2026-08-26-workout-material-list',
    occurredAt: '2026-08-26T14:11:22+07:00',
    title: 'Workout Material List Mobility tersedia',
    description: 'Menambahkan katalog Mobility JSON tervalidasi dengan enam movement detail, route nested di bawah Workout, scheduling berbasis tanggal, preservasi selected date, serta provenance materialId yang tetap immutable pada Workout entry tanpa menggandakan definisi katalog ke PostgreSQL.',
    category: 'Frontend',
  },
  {
    id: '2026-08-26-learning-material-database-expansion',
    occurredAt: '2026-08-26T17:38:10+07:00',
    title: 'English Learning Materials berpindah ke PostgreSQL',
    description: 'Menambahkan learning_materials dan owner-scoped learning_topic_progress, validator seed transactional dengan 20 topic families dan 100 matrix cells, 19 lesson A1 produktif plus Passive/A1 awareness metadata, serta upgrade empat lesson existing tanpa mengubah ID route. Runtime kini memakai endpoint catalogue/detail/progress PostgreSQL; practice, quiz, mastery, review, filter level/topic, published-only state, content version, ownership, OpenAPI, integration tests, production build, Docker health, served routes, dan authenticated API round-trip telah diverifikasi.',
    category: 'Backend',
  },
  {
    id: '2026-08-26-learning-material-a2-batch',
    occurredAt: '2026-08-26T18:53:18+07:00',
    title: 'English Grammar A2 batch tersedia',
    description: 'Mempublikasikan 19 lesson A2 baru dengan rules/pattern, examples bervariasi, common mistakes, practice, objective-aligned quiz, mastery, dan review. Lesson A2 tenses existing tetap dipertahankan; seluruh 20 keluarga A2 kini tersedia di PostgreSQL. Seeder dijalankan dua kali secara idempotent, lalu catalogue, detail, progress owner-scope, test, build, dan deployment verification kembali berhasil.',
    category: 'Backend',
  },
  {
    id: '2026-08-26-learning-material-b1-batch',
    occurredAt: '2026-08-26T19:06:30+07:00',
    title: 'English Grammar B1 batch tersedia',
    description: 'Mempublikasikan 18 lesson B1 baru untuk melengkapi Modals, Passive, Word order, Questions, Negation, Clauses, Articles, Countability, Determiners, Pronouns, Gerunds, Infinitives, Participles, Reported speech, Relative clauses, Conjunctions, Prepositions, dan Comparison. Dua lesson B1 existing tetap dipertahankan; seluruh 20 keluarga B1 kini tersedia di PostgreSQL. Seed, integration test, authenticated detail/progress round-trip, build, dan Docker verification berhasil.',
    category: 'Backend',
  },
  {
    id: '2026-08-26-learning-material-b2-batch',
    occurredAt: '2026-08-26T19:24:30+07:00',
    title: 'English Grammar B2 batch tersedia',
    description: 'Mempublikasikan 20 lesson B2 baru untuk seluruh topic family, termasuk perfect tenses, perfect modals, passive voice lanjutan, third conditional, emphatic word order, complex questions, negative prefixes, reduced relatives, participle clauses, reporting patterns, complex prepositions, dan comparison. Seed idempotent, validator, PostgreSQL integration, authenticated B2 detail/progress round-trip, build, dan Docker verification berhasil.',
    category: 'Backend',
  },
  {
    id: '2026-08-26-learning-material-c1-batch',
    occurredAt: '2026-08-26T19:38:22+07:00',
    title: 'English Grammar C1 batch tersedia',
    description: 'Mempublikasikan 19 lesson C1 baru untuk melengkapi tense nuance, hedging, impersonal passive, mixed conditionals, rhetorical questions, negative inversion, compressed clauses, stylistic articles, nuanced countability, cohesion, advanced gerunds/infinitives/participles, stance reporting, embedded relatives, discourse linking, idiomatic prepositions, dan rhetorical comparison. Lesson word-order C1 existing tetap dipertahankan; seluruh 20 keluarga C1 kini tersedia di PostgreSQL. Seed, integration, authenticated C1 detail/progress round-trip, build, dan Docker verification berhasil.',
    category: 'Backend',
  },
  {
    id: '2026-08-30-nebula-glass-migration',
    occurredAt: '2026-08-30T13:11:26+07:00',
    title: 'Migrasi visual Nebula Glass untuk dashboard Zeno',
    description: 'Menerapkan semantic dark/light tokens, ambient navy-violet-cyan canvas, Level 0–5 glass surfaces, selective shell/overlay blur, restrained elevation, focus-visible, reduced-motion, reduced-transparency fallback, dan parity pada shared, lifestyle, learning, workout, serta auth surfaces tanpa mengubah route, layout, state, API, atau workflow. Verifikasi berhasil: npm test 23/23, npm run build, Docker no-cache build/recreate, container healthy, API health 200, seluruh route dashboard dan representative nested material route 200. Authenticated browser visual review belum dijalankan karena browser harness meminta persetujuan remote debugging dan tidak menyediakan window yang dapat diakses.',
    category: 'Frontend',
  },
  {
    id: '2026-08-30-journal-revision-implementation-brief-audit',
    occurredAt: '2026-08-30T15:47:34+07:00',
    title: 'Implementation brief riwayat revisi Journaling diaudit',
    description: 'Mengaudit alur Journaling dari state dan writer frontend hingga model, store PostgreSQL, endpoint, ownership, migration, serta test backend. Menyusun dan mengeraskan execution brief mandiri 16 bagian untuk Luna dengan immutable full-snapshot revisions, latest snapshot sebagai default, empat reason code wajib, lazy accessible carousel, optimistic concurrency, owner-aware transaction/delete, failure retention, edge cases, acceptance criteria, dan verification matrix. Pekerjaan sesi ini bersifat analysis dan planning; tidak mengklaim implementasi fitur baru.',
    category: 'General',
  },
  {
    id: '2026-08-31-journaling-card-font-profile-content',
    occurredAt: '2026-08-31T10:10:40+07:00',
    title: 'Content card Journaling mengikuti font profile',
    description: 'Memperbaiki selector typography pada content card Journaling agar class journal-rendered markdown-body ikut mengikuti Compact, Standard, dan Expanded. Cakupan diperluas ke isi Markdown, metadata card, editor, preview, reason panel, serta revision history; regression test, production build, Docker recreate, health check, dan served CSS verification berhasil.',
    category: 'Frontend',
  },
  {
    id: '2026-09-07-orbit-command-navigation',
    occurredAt: '2026-09-07T08:59:30+07:00',
    title: 'Orbit Command menggantikan sidebar dashboard Zeno',
    description: 'Menghapus sidebar dan seluruh alokasi lebarnya, lalu menambahkan floating radial navigation dengan 8 menu utama, drill-down pada lingkaran yang sama, route-derived active label, filter permission admin, pagination mobile, modal focus trap, keyboard arrows, Esc, outside click, Back, close, safe-area positioning, light/dark mode, lime active accent, dan reduced-motion fallback. Verifikasi berhasil melalui 27 test, production build, Docker no-cache recreate, container healthy, API/database health 200, 12 route SPA 200, served asset marker, serta browser production-preview desktop/mobile untuk drill-down, selection, Back/Forward, deep link, refresh, permissions, dan zero runtime error.',
    category: 'Frontend',
  },
  {
    id: '2026-09-07-orbit-zeno-size-refinement',
    occurredAt: '2026-09-07T09:46:54+07:00',
    title: 'Orbit navigation diperkecil dan memakai nama Zeno',
    description: 'Mengganti judul pusat Orbit Command menjadi Zeno dan mengurangi diameter maksimum dari 560 px ke 500 px pada desktop serta dari 430 px ke 380 px pada mode compact. Ukuran teks segmen dan target sentuh tetap dipertahankan agar navigasi tetap terbaca dan mudah digunakan.',
    category: 'Frontend',
  },
  {
    id: '2026-09-07-orbit-flower-navigation-refinement',
    occurredAt: '2026-09-07T10:32:01+07:00',
    title: 'Orbit Zeno memakai petal compact',
    description: 'Menyempurnakan navigasi radial menjadi flower layout dengan petal rounded terpisah, ikon di atas label horizontal, hub root hanya berisi wordmark ZENO monospaced, hub Back pada drill-down, active state lime, dan delapan menu utama sekaligus di mobile. Route, permission, pagination untuk sepuluh opsi, keyboard, focus, serta modal behavior tetap dipertahankan. Verifikasi berhasil melalui 27 test, production build, visual QA desktop dan exact viewport 375 x 667 pada root serta drill-down, tanpa overlap, horizontal overflow, atau runtime error.',
    category: 'Frontend',
  },
  {
    id: '2026-09-08-doing-workspace-attributes',
    occurredAt: '2026-09-08T17:20:41+07:00',
    title: 'Doing workspace mendukung perencanaan task lengkap',
    description: 'Merombak Page Doing menjadi workspace task progresif dengan status, priority, time block, estimated dan actual time, category, project, goal, progress, energy focus, dependency, blocked by, notes, carry over, serta completedAt otomatis. Menambahkan schema PostgreSQL, validasi API berbasis karakter Unicode dan batas durasi yang aman untuk INTEGER, ownership, OpenAPI, filter dengan focus restoration, detail, editor responsif, preservasi scroll, draft create/edit saat request gagal, mutasi single-flight untuk mencegah request ganda, input angka satuan, target sentuh mobile 44px, serta dialog hapus dan seluruh alur kalender, expand, completion, dan edit yang ramah keyboard dengan fallback focus, Escape, dan Tab trap. Verifikasi berhasil melalui 50 test frontend, seluruh test serta vet dan build Go, migrasi 14 kolom, Docker no-cache recreate, health API/database, served assets, dan browser QA desktop/mobile hingga viewport 327px untuk create, edit, filter, forced request failure, reload persistence, readback seluruh atribut, completion, delete, keyboard focus, serta penolakan durasi oversized dengan status 400.',
    category: 'General',
  },
  {
    id: '2026-09-08-doing-sql-tenant-isolation',
    occurredAt: '2026-09-08T23:03:21+07:00',
    title: 'Doing memakai SQL-level tenant isolation',
    description: 'Menyelesaikan DOING-BL-001 dengan meneruskan actor user ID dan status admin secara eksplisit ke store Doing. Query list, update, dan delete untuk user biasa kini memuat predicate owner_user_id secara atomik, sedangkan admin menggunakan jalur khusus yang eksplisit. Real PostgreSQL integration dan authenticated API E2E membuktikan dua user terisolasi, update/delete lintas owner tersembunyi sebagai 404 tanpa mutasi, dan akses admin tetap berfungsi.',
    category: 'Backend',
  },
  {
    id: '2026-09-09-doing-live-draft-preservation',
    occurredAt: '2026-09-09T08:32:13+07:00',
    title: 'Draft live Doing aman saat rerender',
    description: 'Menyelesaikan DOING-BL-002 dengan mempertahankan seluruh nilai mentah form create dan edit yang belum disubmit saat quick completion task lain, expand, dialog delete, filter, pencarian, dan aksi kalender memicu rerender. Cancel tetap sengaja membuang draft, sedangkan failure create/edit, focus, dan internal list scroll tetap dipertahankan. Verifikasi berhasil melalui focused contract 3/3, full frontend test 50/50, production build, audit 0 vulnerability, Docker recreate healthy, API/database health, serta browser E2E desktop dan mobile.',
    category: 'Frontend',
  },
  {
    id: '2026-09-09-doing-astral-unicode-validation',
    occurredAt: '2026-09-09T09:12:24+07:00',
    title: 'Batas karakter Unicode Doing selaras',
    description: 'Menyelesaikan DOING-BL-003 dengan mengganti maxlength native UTF-16 pada tujuh field teks editor Doing menjadi validasi Unicode code point yang selaras dengan Go utf8.RuneCountInString dan OpenAPI maxLength. Browser production membuktikan tepat 160 emoji astral diterima dan tersimpan ke PostgreSQL, 161 ditolak dengan pesan inline tanpa persistence, serta kombinasi ASCII, BMP, astral, dan custom category tetap berfungsi. Verifikasi juga mencakup focused RED-GREEN, 51 test frontend, seluruh test/vet/build Go, OpenAPI parse, Docker healthy, served bundle, dan cleanup fixture.',
    category: 'Frontend',
  },
  {
    id: '2026-09-09-doing-narrow-calendar-geometry',
    occurredAt: '2026-09-09T09:45:08+07:00',
    title: 'Kalender Doing aman pada viewport 327px',
    description: 'Menyelesaikan DOING-BL-004 dengan mempertahankan hit-area seluruh day cell minimal 44 x 44px. Pada viewport 327px, kalender memakai scrolling horizontal internal dengan instruksi terlihat, region yang dapat difokuskan, dukungan keyboard, serta seluruh kolom dapat dijangkau tanpa document-level horizontal overflow. Viewport 390px dan desktop menampilkan satu minggu utuh tanpa scroll. Verifikasi mencakup focused RED-GREEN, 52 test frontend, production build, audit 0 vulnerability, Docker no-cache recreate healthy, API/database health, served bundle, pengukuran bounding box 327/390/desktop, keyboard day selection, dan screenshot.',
    category: 'Frontend',
  },
  {
    id: '2026-09-09-doing-mobile-editor-touch-targets',
    occurredAt: '2026-09-09T10:20:14+07:00',
    title: 'Kontrol editor Doing 44px di mobile',
    description: 'Menyelesaikan DOING-BL-005 dengan menaikkan seluruh input, select, textarea action area, checkbox, dan tombol editor Doing menjadi minimal 44 x 44px pada viewport hingga 680px tanpa mengubah density desktop. Browser production mengukur 19 kontrol dengan minimum 44 x 44px, tanpa overlap antar-kontrol, clipping, atau document overflow pada 327px dan 390px; seluruh kontrol juga mempertahankan focus ring keyboard dan checkbox dapat ditoggle dengan Space. Verifikasi mencakup focused RED-GREEN, 53 test frontend, production build, audit 0 vulnerability, Docker no-cache recreate healthy, API/database health, served CSS, dan screenshot 327/390/desktop.',
    category: 'Frontend',
  },
  {
    id: '2026-09-09-doing-openapi-runtime-contract',
    occurredAt: '2026-09-09T10:47:15+07:00',
    title: 'Kontrak runtime OpenAPI Doing dilengkapi',
    description: 'Menyelesaikan DOING-BL-006 dengan mendokumentasikan CookieAuth pada GET, POST, PUT, dan DELETE Doing; requirement X-CSRF-Token pada seluruh mutation endpoint; serta response 400, 401, 403, dan 404 yang benar-benar relevan dengan middleware dan handler runtime. Contract test menjalankan probe runtime per method dan memverifikasi kontrak terpublikasi. Focused RED-GREEN, seluruh test Go, vet, build backend, dan parse OpenAPI YAML berhasil.',
    category: 'Backend',
  },
  {
    id: '2026-09-09-doing-visible-mutation-busy-state',
    occurredAt: '2026-09-09T11:32:09+07:00',
    title: 'Mutasi Doing menampilkan status sibuk',
    description: 'Menyelesaikan DOING-BL-007 dengan menampilkan status live spesifik saat task dibuat, diedit, ditandai selesai, atau dihapus. Selama request aktif, seluruh kontrol mutasi relevan, field editor, dan cancel dinonaktifkan; setelah success maupun failure semuanya aktif kembali, draft dan focus tetap dipertahankan, serta double submit tetap hanya menghasilkan satu request. Verifikasi mencakup focused RED-GREEN contract, 54 test frontend, TypeScript dan production build, audit 0 vulnerability, Docker recreate healthy, API/database health, served bundle, serta authenticated browser E2E untuk create, edit, toggle, delete, success, failure, dan single-flight.',
    category: 'Frontend',
  },
  {
    id: '2026-09-09-doing-orbit-action-non-overlap',
    occurredAt: '2026-09-09T11:56:22+07:00',
    title: 'Orbit tidak lagi menutup aksi editor Doing',
    description: 'Menyelesaikan DOING-BL-008 dengan memindahkan dock trigger Orbit secara deterministik di antara empat sudut viewport ketika posisinya berpotensi beririsan dengan submit atau cancel editor Doing. Posisi dihitung ulang saat render, resize, document scroll, dan internal list scroll; halaman tanpa editor tetap memakai posisi kanan bawah. Verifikasi mencakup focused RED-GREEN 2/2, 56 test frontend, TypeScript dan production build, audit 0 vulnerability, Docker recreate healthy, API/database health, served bundle, serta authenticated browser QA pada 1440x1200, 390x844, dan 327x667 dengan 624 sampel scroll, overlap area nol, real pointer submit/cancel, keyboard submit, dan keyboard Orbit pada halaman lain.',
    category: 'Frontend',
  },
  {
    id: '2026-09-09-doing-create-date-race-fix',
    occurredAt: '2026-09-09T13:33:20+07:00',
    title: 'Task Doing baru tetap masuk ke tanggal pengiriman',
    description: 'Memperbaiki race condition pada create Doing ketika pengguna mengganti tanggal kalender sebelum respons API selesai. Task hasil create kini dimasukkan ke bucket tanggal canonical dari respons server, bukan tanggal global yang sedang dipilih. Regression test RED-GREEN menjaga assignment tetap mengikuti created.date setelah navigasi kalender.',
    category: 'Frontend',
  },
  {
    id: '2026-09-09-orbit-sequential-motion',
    occurredAt: '2026-09-09T14:48:18+07:00',
    title: 'Animasi Orbit tampil berurutan',
    description: 'Menyempurnakan Radial Navigation agar hub tengah muncul lebih dulu, lalu delapan petal navigasi masuk satu per satu dengan motion cepat dan smooth. Saat ditutup, petal menghilang dalam urutan terbalik sebelum hub tengah, dengan fallback reduced motion tetap dipertahankan. Verifikasi mencakup focused RED-GREEN, 58 test frontend, TypeScript, dan production build.',
    category: 'Frontend',
  },
  {
    id: '2026-09-09-orbit-submenu-transition-continuity',
    occurredAt: '2026-09-09T15:07:28+07:00',
    title: 'Transisi submenu Orbit bebas kedip',
    description: 'Memperbaiki blitz saat membuka Account, Lifestyle, Workout, dan menu lain yang memiliki submenu. Pergantian layer kini hanya melepas petal lama; backdrop dan hub tetap terlihat, lalu petal submenu masuk berurutan tanpa mengulang animasi pembukaan seluruh Orbit. Verifikasi mencakup regression test RED-GREEN, 59 test frontend, TypeScript, dan production build.',
    category: 'Frontend',
  },
  {
    id: '2026-09-09-orbit-draggable-trigger',
    occurredAt: '2026-09-09T15:34:27+07:00',
    title: 'Tombol Orbit dapat dipindahkan',
    description: 'Membuat trigger Orbit dapat digeser dengan pointer ke seluruh viewport dan dipindahkan lewat Alt plus tombol panah. Posisi selalu dijepit dengan inset aman agar tombol tidak keluar halaman, tetap dipertahankan saat dashboard render ulang, dan kembali menyesuaikan saat viewport berubah. Ketika dibuka, dialog radial memilih sisi dengan ruang terbesar di sekitar trigger lalu dijepit agar seluruh menu tetap terlihat. Verifikasi mencakup geometry dan interaction contract RED-GREEN, 61 test frontend, TypeScript, dan production build.',
    category: 'Frontend',
  },
  {
    id: '2026-09-09-activity-trail-redesign',
    occurredAt: '2026-09-09T19:34:52+07:00',
    title: 'Activity Log memakai timeline audit per pengguna',
    description: 'Merombak Activity Log mengikuti referensi visual menjadi timeline kronologis per hari dan pengguna, dengan rail waktu, avatar actor, card event beraksen entity, pencarian, filter pengguna dan periode, collapse group, detail event yang dapat dibuka, progressive reveal, serta komposisi responsif dark/light tanpa mengubah kontrak API activity dan ownership.',
    category: 'Frontend',
  },
  {
    id: '2026-09-09-activity-session-gap-splitting',
    occurredAt: '2026-09-09T19:47:46+07:00',
    title: 'Activity pengguna dipisah setelah jeda satu jam',
    description: 'Menyempurnakan pengelompokan Activity Log agar event dari pengguna yang sama tetap berada dalam satu card saat jedanya maksimal 60 menit, tetapi membentuk card sesi baru ketika jeda antar-event lebih dari 60 menit. Pemisahan tetap independen per pengguna dan hari, dengan urutan terbaru dipertahankan.',
    category: 'Frontend',
  },
  {
    id: '2026-09-10-workout-trail-focus-mode',
    occurredAt: '2026-09-10T16:10:10+07:00',
    title: 'Workout Trail dan Focus Mode tersedia',
    description: 'Menyelesaikan Workout Trail dan Focus Mode dengan planner mingguan multi-sesi, model sesi ke gerakan ke set, target dan hasil aktual terpisah, gerakan adaptif strength, bodyweight, cardio, mobility, dan interval, timer sesi serta istirahat yang pulih setelah refresh, pencatatan retry single-flight tanpa kehilangan draft, partial completion, duplikasi plan-only, template, filter riwayat, previous result yang sebanding, dan ringkasan jujur. Verifikasi lulus melalui 80 test frontend, production build, served UI desktop dan mobile, browser QA recovery, save-failure, klik cepat, responsive-accessibility geometry, real API dan PostgreSQL readback, serta cleanup fixture nol.',
    category: 'General',
  },
  {
    id: '2026-09-12-auth-playground-alignment',
    occurredAt: '2026-09-12T16:55:50+07:00',
    title: 'Login Zeno menyatu dengan Playground',
    description: 'Menyelaraskan halaman Login, Register, dan Email Verification dengan desain Zeno Playground melalui panel lime editorial, surface off-white dan charcoal, aksen cobalt, kartu 24px, tombol pill, Outfit dan DM Mono, serta parity light/dark dan responsive mobile. Alur autentikasi, validasi, route, dan keamanan tetap dipertahankan. Verifikasi mencakup contract test, full frontend test, production build, serta browser QA light/dark pada 390px, 768px, dan 1440px dengan axe tanpa violation.',
    category: 'Frontend',
  },
  {
    id: '2026-09-12-dashboard-typography-alignment',
    occurredAt: '2026-09-12T17:55:03+07:00',
    title: 'Tipografi dashboard selaras dengan Zeno Playground',
    description: 'Menyelaraskan hierarki tipografi dashboard dengan landing page menggunakan Outfit sebagai suara utama dan DM Mono secara selektif untuk metadata. Skala Compact, Standard, dan Expanded kini memiliki body, heading, control, line-height, weight, serta tracking yang lebih nyaman tanpa mengubah preferensi tersimpan. Responsive fix menjaga status topbar dan CTA Journaling bebas benturan dengan Orbit. Verifikasi mencakup RED-GREEN contract, 96 test frontend, production build, serta 36 skenario browser pada Overview dan Journaling untuk tiga viewport, tiga profil, light/dark, tanpa overflow, page error, atau axe violation.',
    category: 'Frontend',
  },
  {
    id: '2026-09-14-aurora-ribbon-dashboard-background',
    occurredAt: '2026-09-14T12:07:48+07:00',
    title: 'Aurora Ribbon diterapkan pada seluruh dashboard Zeno',
    description: 'Menambahkan satu background Aurora Ribbon pada dashboard shell dengan pita lime dan biru yang lembut, blur terpusat pada artwork, komposisi perimeter yang sama untuk dark dan light mode, responsive intensity, serta reduced-motion fallback. UI, Orbit Command, route, auth, API, CRUD, autosave, font profile, dan persistence tetap dipertahankan. Verifikasi berhasil melalui 97 test frontend, production build, Docker no-cache build/recreate, container healthy, browser QA Overview dan Journaling dark/light, halaman panjang, mobile tanpa overflow, Orbit, reduced motion, serta landing-login flow tanpa kebocoran styling.',
    category: 'Frontend',
  },
];
